# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  displayName: Install Dependencies
  inputs:
    script: 'yarn install'

- task: CmdLine@2
  displayName: Install GitPython Dependency
  inputs:
    script: 'python3 -m pip install GitPython'

- task: CmdLine@2
  displayName: Install GitPython Dependency
  inputs:
    script: 'python3 -m pip install ruamel_yaml'

- task: CmdLine@2
  displayName: Clone frdoiddata
  inputs:
    script: 'git clone https://gitlab.com/podverse/fdroiddata.git' 
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Clone fdroidserver
  inputs:
    script: 'git clone https://gitlab.com/fdroid/fdroidserver.git'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Copy podverse yml to metadata
  inputs:
    script: 'cp $(Build.Repository.LocalPath)/fdroid/com.podverse.fdroid.yml fdroiddata/metadata'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Log podverse frdoid yml 
  inputs:
    script: 'cat fdroid/com.podverse.fdroid.yml'

- task: CmdLine@2
  displayName: Log fdroiddata metadata podverse yml
  inputs:
    script: 'cat fdroiddata/metadata/com.podverse.fdroid.yml'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Read Metadata
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid readmeta'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Rewrite Metadata
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid rewritemeta com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Lint podverse fdroid config file
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid lint com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Build fdroid podverse
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid build -v -l com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Where is it - Agent.BuildDriectory
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Where is it - Agent.BuildDirectory fdroiddata
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Where is it - Agent.BuildDirectory build
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/build

- task: CmdLine@2
  displayName: Where is it - Agent.BuildDirectory build com podverse fdroid
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/build/com.podverse.fdroid/

- task: CmdLine@2
  displayName: Where is it - Agent.BuildDirectory build com podverse fdroid android
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/build/com.podverse.fdroid/android

- task: CmdLine@2
  displayName: Where is it - fdroidserver 1
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/fdroidserver

- task: CmdLine@2
  displayName: Where is it - fdroidserver 2
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/fdroidserver/fdroid

- task: CmdLine@2
  displayName: Where is it - fdroidserver 3
  inputs:
    script: 'pwd'
    workingDirectory: $(Agent.BuildDirectory)/fdroidserver/fdroid/android

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/com.podverse.fdroid/android/app/build/outputs/apk/release'
    ArtifactName: 'drop'
    publishLocation: 'Container'
